const SUPABASE_URL = 'https://lzlcmmmftqvllaqzuivc.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bGNtbW1mdHF2bGxhcXp1aXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNzgwMzQsImV4cCI6MjA5Mjc1NDAzNH0.Gxqc0J1mEKhw18VKSQA3Q2-ZDXEvrj5PGIrKaf_e-AU';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
NEXT_PUBLIC_SUPABASE_URL=https://lzlcmmmftqvllaqzuivc.supabase.co
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_IrIb9ufL08ZkuhH4q5M8rQ_HcYYYsn9